// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmjhfTCXRwP-d8M8eI4i1YPXtXoZT31qs',
    appId: '1:179798066529:web:4e2342f6079da9c25a7120',
    messagingSenderId: '179798066529',
    projectId: 'care-app-1',
    authDomain: 'care-app-1.firebaseapp.com',
    storageBucket: 'care-app-1.appspot.com',
    measurementId: 'G-MFBPW5B2NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5fD4NxwTgMjlt4uQMdUSEHU000Td3JTk',
    appId: '1:179798066529:android:0cc8a8c83aa29d995a7120',
    messagingSenderId: '179798066529',
    projectId: 'care-app-1',
    storageBucket: 'care-app-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1S7c95o7wznrt0oRujzUdU5QNe9meEaI',
    appId: '1:179798066529:ios:a36d590adeee816f5a7120',
    messagingSenderId: '179798066529',
    projectId: 'care-app-1',
    storageBucket: 'care-app-1.appspot.com',
    iosBundleId: 'com.example.careAppTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1S7c95o7wznrt0oRujzUdU5QNe9meEaI',
    appId: '1:179798066529:ios:a36d590adeee816f5a7120',
    messagingSenderId: '179798066529',
    projectId: 'care-app-1',
    storageBucket: 'care-app-1.appspot.com',
    iosBundleId: 'com.example.careAppTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmjhfTCXRwP-d8M8eI4i1YPXtXoZT31qs',
    appId: '1:179798066529:web:721194c085c39fb95a7120',
    messagingSenderId: '179798066529',
    projectId: 'care-app-1',
    authDomain: 'care-app-1.firebaseapp.com',
    storageBucket: 'care-app-1.appspot.com',
    measurementId: 'G-82Y9QCE7GB',
  );
}
